export default [
  {
    id: 1,
    name: 'Carla',
    age: 25,
    address: 'Carlsbad, CA',
    image: require('../assets/Misc/girl2.jpg'),
    lifepath: 1,
    destiny: 99,
    personality: 3,
    desire: 8,
  },
  {
    id: 2,
    name: 'Ann',
    age: 22,
    address: 'Riverside, CA',
    image: require('../assets/Misc/girl1.jpg'),
    lifepath: 3,
    destiny: 75,
    personality: 4,
    desire: 3,
  },
  {
    id: 3,
    name: 'Julie',
    age: 28,
    address: 'San Jose, CA',
    image: require('../assets/Misc/girl3.jpg'),
    lifepath: 6,
    destiny: 89,
    personality: 6,
    desire: 10,
  },
];
